[workspace]
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]
name = "green-ci-demo"
platforms = ["osx-arm64"]
version = "0.1.0"

[environments]
template = ["template"]

[tasks]

[dependencies]

[feature.template.dependencies]
copier = "*"
